CREATE TABLE "DEC_CATEGORIA" ( "ID" NUMBER(3),
"ABREVIATURA" VARCHAR2(15) NOT NULL ,
"DESCRICAO" VARCHAR2(80) NOT NULL ,
"OBSERVACAO" VARCHAR2(120),
"STATUS" NUMBER(1) DEFAULT 0 NOT NULL,
PRIMARY KEY ("ID"));

create sequence "SQ_DEC_CATEGORIA" MINVALUE 1 MAXVALUE 9999999999 start with 1 increment by 1 nocache;